name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v5
      - name: Java einrichten
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: JavaFX herunterladen und entpacken
        run: |
          wget https://download2.gluonhq.com/openjfx/21.0.2/openjfx-21.0.2_linux-x64_bin-sdk.zip
          unzip openjfx-21.0.2_linux-x64_bin-sdk.zip
      - name: JUnit herunterladen
        run: |
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.2/junit-platform-console-standalone-1.10.2.jar
      - name: JavaFX lib-Inhalt anzeigen
        run: |
          ls -l javafx-sdk-21.0.2/lib
      - name: Kompilieren (ohne Tests)
        run: |
          find src/com/barpos -name '*.java' ! -name 'ProductTest.java' > sources.txt
          javac --module-path $GITHUB_WORKSPACE/javafx-sdk-21.0.2/lib -d bin src/module-info.java @sources.txt
      - name: JAR erstellen
        run: |
          jar cfm BarPOSSystem.jar manifest.txt -C bin .
      - name: Tests kompilieren und ausführen
        run: |
          javac -cp junit-platform-console-standalone-1.10.2.jar:bin --module-path $GITHUB_WORKSPACE/javafx-sdk-21.0.2/lib -d bin src/com/barpos/ProductTest.java
          java -jar junit-platform-console-standalone-1.10.2.jar --class-path bin --scan-class-path
