name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
      - name: Java einrichten
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: JavaFX herunterladen und entpacken
        run: |
          wget https://download2.gluonhq.com/openjfx/21.0.2/openjfx-21.0.2_linux-x64_bin-sdk.zip
          unzip openjfx-21.0.2_linux-x64_bin-sdk.zip
      - name: JavaFX lib-Inhalt anzeigen
        run: |
          ls -l javafx-sdk-21.0.2/lib
      - name: Kompilieren
        run: |
          javac --module-path $GITHUB_WORKSPACE/javafx-sdk-21.0.2/lib --add-modules javafx.controls,javafx.fxml -d bin src/module-info.java src/com/barpos/*.java
      - name: JAR erstellen
        run: |
          jar cfm BarPOSSystem.jar manifest.txt -C bin .
      - name: (Optional) Tests ausführen
        run: echo "Hier könnten Tests ausgeführt werden."
